### ISSUE TITLE
In sample `velodyne_node_container.launch.py` the crop box filters should come after cloud rectification

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/sample_sensor_kit_launch#28]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I think the order of components in the [velodyne_node_container.launch.py](https://github.com/autowarefoundation/sample_sensor_kit_launch/blob/main/common_sensor_launch/launch/velodyne_node_container.launch.py) node is wrong. Currently, it is:
1. convert velodyne -> pointcloud
2. filter out vehicle and mirror with crop box
3. correct cloud distortion
4. filter out noise/rain

So the crop box filtering is done on the unrectified (distorted) pointcloud. It seems more logical that any correction on the cloud should be made first:
1. convert velodyne -> pointcloud
3. correct cloud distortion
2. filter out vehicle and mirror with crop box
4. filter out noise/rain

### Expected behavior

crop box filter should process rectified cloud

### Actual behavior

crop box filter process a distorted cloud

### Steps to reproduce

N/A

**Comment by miursh** [comment]
Could you explain more detail why you think that is more logical?

Since LiDAR is moving along with the vehicle, I believe the pointcloud obtained from vehicle/mirror is NOT distorted from the beginning.
If undistortion is apply to the the points from vehicle, unintended correction is applied, the result becomes distorted points. It makes it difficult to filter by rectangular (the crop box filter).

**Comment by VRichardJP** [comment]
@miursh 
You are right, my bad!
